WebClient/Models/Camera.cs
namespace WebClient.Models
{
    public class Camera
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Rover_Id { get; set; }
        public string Full_Name { get; set; }
    }
}

WebClient/Models/Photo.cs
using System;

namespace WebClient.Models
{
    public class Photo
    {
        public int Id { get; set; }

        public int Sol { get; set; }

        public Camera Camera { get; set; }

        public string Img_src { get; set; }

        public string Date { get; set; }

        
    }
}

WebClient/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

WebClient/Controllers/MarsRoverController.cs
using System.Collections.Generic;
using MarsRover;
using MarsRover.Controller;
using Microsoft.AspNetCore.Mvc;
using WebClient.ViewModel;

namespace WebClient.Controllers
{
    public class MarsRoverController : Controller
    {
        public IActionResult Index()
        {
            // string date = "02 / 27 / 17";
            // return View (CreateViewModel( "02 / 27 / 17"));
           return View();
        }

        public ActionResult Download (string date = null, string url = null)
        {
            return View(CreateViewModel(date = "02 / 27 / 17", url));
        }

        public RoverPhotosViewModel CreateViewModel(string date, string url)
        {
            RoverPhotosViewModel roverPhotosViewModel = new RoverPhotosViewModel();
            roverPhotosViewModel.SelectedDate = date;
            var key = "DEMO_Key";
            var manager = new DownloadPhoto();
            manager.DownloadPhotoAsync(date, key, url).Wait();
            return roverPhotosViewModel;
        }

        public void DownloadPhotoByDate(string date, string url)
        {
            var key = "DEMO_Key";
            string dateT = "02 / 27 / 17";
            var manager = new DownloadPhoto();
            manager.DownloadPhotoAsync(dateT, key, url).Wait();
            
            
        }
    }
}

WebClient/Views/Home/Index.cshtml
@using WebClient.ViewModel

@model WebClient.ViewModel.RoverPhotosViewModel

@{
    ViewData["Title"] = "Home Page";
}
@{
    List<SelectListItem> dateListItems = new List<SelectListItem>
    {
        new SelectListItem {Value = "0", Text = "02/27/17"},
        new SelectListItem {Value = "1", Text = "June 2, 2018"},
        new SelectListItem {Value = "2", Text = "Jul-13-2016"},
        new SelectListItem {Value = "3", Text = "April 31, 2018"}
    };
}

<!DOCTYPE html>
<html>
<head>
    <style>
        .header img {
            background: #555;
            float: left;
        }

        .header h1 {
            position: relative;
        }

        .input {
            position: relative;
        }
    </style>
</head>
<body>

</body>
</html>

<div class="text-center">
    <div class="header">
        <img src="~/Content/logo/download.png" alt="logo" width="100" />
        <h1 class="display-4">Mars Rover Photos</h1>
    </div>
    <div>
        <p class="col-md-12">
            This API is designed to collect image data gathered by NASA's Curiosity, Opportunity, and Spirit rovers on Mars and make it more easily available to other developers, educators, and citizen scientists. This API is maintained by Chris Cerami.

            Each rover has its own set of photos stored in the database, which can be queried separately. There are several possible queries that can be made against the API. Photos are organized by the sol (Martian rotation or day) on which they were taken, counting up from the rover's landing date. A photo taken on Curiosity's 1000th Martian sol exploring Mars, for example, will have a sol attribute of 1000. If instead you prefer to search by the Earth date on which a photo was taken, you can do that too.

            Along with querying by date, results can also be filtered by the camera with which it was taken and responses will be limited to 25 photos per call. Queries that should return more than 25 photos will be split onto several pages, which can be accessed by adding a 'page' param to the query.
        </p>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">Select the date</div>
            <div class="panel-body">
                @Html.DropDownListFor(Model => Model.SelectedDate, dateListItems, "Select Date", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SelectedDate)
            </div>
        </div>
    </div>
    
    <div class="col-md-9"><a href="https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?earth_date=2015-6-3&amp;api_key=DEMO_KEY">See the Raw data</a>.</div>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js">

    $("#SelectedDate").change(function () {
        GetData();
    });

    function GetData() {
        var date = $("#SelectedDate").val();
        alert(date);
        if (date != null) {
            pleaseWait();
            $.ajax({
                type: "POST",
                url: "@Url.Action("DownloadPhotoByDate", "MarsRover")",
                data: {Date : date},
                async: true,
                success: function(data) {
                    bootbox.hideAll();
                    bootbox.alert({
                        title: "Service Alert Raw data format",
                        message:
                            '<textarea class="form-control" style="min-width: 100%;border: none" rows="20" name="editComment">' +
                                data +
                                '</textarea>',
                        closeButton: false
                    });
                },
                error: function(textStatus, errorThrown, errorMessage) {
                    bootbox.hideAll();
                    bootbox.alert({
                        message: GetBootstrapAlertStyle(errorMessage, "danger"),
                        closeButton: false
                    });
                }
            });
        } else {
            bootbox.alert({
                message: GetBootstrapAlertStyle("Please select a Jurisdiction", "info"),
                closeButton: false
            });
        }
    }

</script>

WebClient/Views/MarsRover/Index.cshtml
@using System.IO
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>Photo!</p>

@foreach (var imgPath in Directory.GetFiles("Content/images", "*.jpg"))
{
    var img = new FileInfo(imgPath);
    <img src="@Url.Content(string.Format("~/Content/images/{0}", img.Name))" , width="200" />
}

<script type="text/javascript">
    var folder = "C:/MarsRover/2017-02-27";

    $.ajax({
        url: folder,
        success: function (data) {
            $(data).find("a").attr("href", function (i, val) {
                if (val.match(/\.(jpe?g|png|gif)$/)) {
                    $("body").append("
                        < img src = '" + folder + val + "' > ");
                }
            });
        }
</script>

WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebClient</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - WebClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", false)
</body>
</html>